name: "Terraform CI/CD"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan Dev
        run: terraform plan -var-file=environments/dev.tfvars
        
      - name: Terraform Apply Dev
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -var-file=environments/dev.tfvars
        
      # Ajoute des étapes similaires pour test et prod avec approbation manuelle
